import { prisma } from '@/lib/db'
import { Prisma } from '@prisma/client'

/**
 * Prisma has no native type for pgvector's `vector` column - Question.embedding
 * is declared as `Unsupported("vector(768)")` in schema.prisma, which Prisma
 * Client can't read or write through its normal typed methods. Every access to
 * that column goes through the raw-SQL helpers in this file instead.
 */

// Must match worker/src/providers/llm.py's EMBEDDING_MODEL/EMBEDDING_DIMENSIONS
// and the pgvector column width - all three have to agree or writes/searches break.
const EMBEDDING_MODEL = 'gemini-embedding-001'
const EMBEDDING_DIMENSIONS = 768

// pgvector's wire format for a vector literal is a plain string like "[0.1,-0.2,0.3]",
// cast to the column type with `::vector` in the SQL itself.
function toVectorLiteral(embedding: number[]): string {
  return `[${embedding.join(',')}]`
}

function parseVectorLiteral(text: string | null): number[] | null {
  if (!text) return null
  return text
    .slice(1, -1) // strip the surrounding [ ]
    .split(',')
    .map(Number)
}

/** Writes one question's embedding (generated by the worker via Gemini's embedding API). */
export async function setQuestionEmbedding(questionId: string, embedding: number[] | null): Promise<void> {
  if (!embedding) return // worker couldn't embed this question; leave the column null rather than fail the job
  const literal = toVectorLiteral(embedding)
  await prisma.$executeRaw`UPDATE "Question" SET embedding = ${literal}::vector WHERE id = ${questionId}`
}

/** Fetches stored embeddings for a set of question ids (e.g. when reusing a duplicate-detected paper). */
export async function getQuestionEmbeddings(questionIds: string[]): Promise<Record<string, number[] | null>> {
  if (questionIds.length === 0) return {}

  const rows = await prisma.$queryRaw<{ id: string; embedding: string | null }[]>(
    Prisma.sql`SELECT id, embedding::text as embedding FROM "Question" WHERE id IN (${Prisma.join(questionIds)})`
  )

  const result: Record<string, number[] | null> = {}
  for (const row of rows) {
    result[row.id] = parseVectorLiteral(row.embedding)
  }
  return result
}

/**
 * Embeds free-form text (a student's chat message) via Gemini's embedding API,
 * using taskType RETRIEVAL_QUERY - the "query side" of asymmetric search, paired
 * with the RETRIEVAL_DOCUMENT embeddings the worker generates for exam questions
 * (worker/src/providers/llm.py). Using the matching task type on each side is
 * what makes the similarity comparison meaningful, not just dimension-compatible.
 * Returns null on any failure so callers can fall back to lexical search
 * instead of breaking the chat.
 */
export async function embedQuery(text: string, apiKey: string): Promise<number[] | null> {
  try {
    const res = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${EMBEDDING_MODEL}:embedContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          content: { parts: [{ text: text.slice(0, 8000) }] }, // guard against pathological input length
          taskType: 'RETRIEVAL_QUERY',
          outputDimensionality: EMBEDDING_DIMENSIONS,
        }),
      }
    )
    if (!res.ok) return null
    const data = await res.json()
    return data.embedding?.values ?? null
  } catch {
    return null
  }
}

export type SimilarQuestionMatch = { id: string; distance: number }

/**
 * pgvector's `<=>` cosine-distance operator (smaller = more similar) - the core
 * of semantic retrieval: finds exam questions whose meaning is closest to the
 * given query vector, even when the wording is completely different. Scoped to
 * one course; optionally narrowed further to a topic name. Questions with no
 * embedding yet (e.g. ingested before this feature existed) are excluded rather
 * than sorted arbitrarily.
 */
export async function findSimilarQuestionIds(
  queryEmbedding: number[],
  courseCode: string,
  options: { topicName?: string; limit?: number } = {}
): Promise<SimilarQuestionMatch[]> {
  const literal = toVectorLiteral(queryEmbedding)
  const limit = options.limit ?? 8

  const topicFilter = options.topicName
    ? Prisma.sql`AND EXISTS (
        SELECT 1 FROM "QuestionTopic" qt
        JOIN "Topic" t ON qt."topicId" = t.id
        WHERE qt."questionId" = q.id AND t."topicName" ILIKE ${'%' + options.topicName + '%'}
      )`
    : Prisma.empty

  return prisma.$queryRaw<SimilarQuestionMatch[]>(Prisma.sql`
    SELECT q.id, (q.embedding <=> ${literal}::vector) AS distance
    FROM "Question" q
    JOIN "Paper" p ON q."paperId" = p.id
    JOIN "Course" c ON p."courseId" = c.id
    WHERE c.code = ${courseCode}
      AND q.embedding IS NOT NULL
      ${topicFilter}
    ORDER BY distance ASC
    LIMIT ${limit}
  `)
}
